shell.run("delete quarry.lua")
shell.run("delete flex.lua")
shell.run("delete dig.lua")
shell.run("https://raw.githubusercontent.com/chaos511/ccprograms/master/quarry.lua quarry.lua")
shell.run("https://raw.githubusercontent.com/chaos511/ccprograms/master/flex.lua flex.lua")
shell.run("https://raw.githubusercontent.com/chaos511/ccprograms/master/dig.lua eGkHs4Kk dig.lua")