shell.run("delete yatqp.lua")
shell.run("delete flex.lua")
shell.run("delete dig.lua")
shell.run("wget https://raw.githubusercontent.com/chaos511/ccprograms/master/v0/yatqp.lua yatqp.lua")
shell.run("wget https://raw.githubusercontent.com/chaos511/ccprograms/master/v0/flex.lua flex.lua")
shell.run("wget https://raw.githubusercontent.com/chaos511/ccprograms/master/v0/dig.lua dig.lua")
