shell.run("delete flex.lua")
shell.run("delete dig.lua")
shell.run("delete home.lua")
shell.run("delete sethome.lua")
shell.run("delete help.lua")
shell.run("delete setboundingbox.lua")
shell.run("delete yatqp.lua")
shell.run("delete setautofuel.lua")

-- shell.run("mkdir lib")
shell.run("wget https://raw.githubusercontent.com/chaos511/ccprograms/master/v1/yatqp/home.lua home.lua")
shell.run("wget https://raw.githubusercontent.com/chaos511/ccprograms/master/v1/yatqp/sethome.lua sethome.lua")
shell.run("wget https://raw.githubusercontent.com/chaos511/ccprograms/master/v1/yatqp/flex.lua flex.lua")
shell.run("wget https://raw.githubusercontent.com/chaos511/ccprograms/master/v1/yatqp/dig.lua dig.lua")
shell.run("wget https://raw.githubusercontent.com/chaos511/ccprograms/master/v1/yatqp/help.lua help.lua")
shell.run("wget https://raw.githubusercontent.com/chaos511/ccprograms/master/v1/yatqp/setboundingbox.lua setboundingbox.lua")
shell.run("wget https://raw.githubusercontent.com/chaos511/ccprograms/master/v1/yatqp/yatqp.lua yatqp.lua")
shell.run("wget https://raw.githubusercontent.com/chaos511/ccprograms/master/v1/yatqp/setautofuel.lua setautofuel.lua")
